SELECT P.RIOT_ID, M.NOME_MAPA, ((P.KILLS + P.ASSISTS)/P.DEATHS) AS KDA
FROM PARTICIPA P INNER JOIN PARTIDA M ON P.ID_PARTIDA = M.ID_PARTIDA
WHERE ((P.KILLS + P.ASSISTS)/P.DEATHS) >
      (SELECT (SUM(P1.KILLS) + SUM(P1.ASSISTS))/SUM(P1.DEATHS) AS AVG_KDA
       FROM PARTICIPA P1
       GROUP BY ID_PARTIDA
       HAVING P1.ID_PARTIDA = P.ID_PARTIDA);