CREATE TABLE Jogador(
    RIOT_ID VARCHAR(21) PRIMARY KEY
);

CREATE TABLE Arma(
    NOME VARCHAR(30) PRIMARY KEY,
    TIPO VARCHAR(30) NOT NULL,
    PRECO NUMBER(4, 0) NOT NULL
);

CREATE TABLE Skin(
    ID_SKIN NUMBER(3, 0) PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL UNIQUE,
    PRECO NUMBER(4, 0) NOT NULL
);

CREATE TABLE Agente(
    NOME_AGENTE VARCHAR(30) PRIMARY KEY,
    HAB1 VARCHAR(30) NOT NULL UNIQUE,
    HAB2 VARCHAR(30) NOT NULL UNIQUE,
    HAB3 VARCHAR(30) NOT NULL UNIQUE,
    ULT VARCHAR(30) NOT NULL UNIQUE,
    FUNC VARCHAR(30) NOT NULL
);

CREATE TABLE Mapa(
    NOME_MAPA VARCHAR(15) PRIMARY KEY,
    QNTD_BOMBS NUMBER(1, 0) NOT NULL
);

CREATE TABLE Partida(
    ID_PARTIDA VARCHAR(8) PRIMARY KEY,
    NOME_MAPA VARCHAR(15) NOT NULL,
    CONSTRAINT FK_PARTIDA FOREIGN KEY (NOME_MAPA) REFERENCES Mapa(NOME_MAPA)
);

CREATE TABLE MataMata(
    ID_PARTIDA VARCHAR(8) PRIMARY KEY,
    GANHADOR VARCHAR(21) NOT NULL,
    CONSTRAINT FK_MATAMATA FOREIGN KEY (ID_PARTIDA) REFERENCES Partida(ID_PARTIDA)
);

CREATE TABLE Disparada(
    ID_PARTIDA VARCHAR(8) PRIMARY KEY,
    CONSTRAINT FK_DISPARADA FOREIGN KEY (ID_PARTIDA) REFERENCES Partida(ID_PARTIDA)
);

CREATE TABLE ArmasDisparada(
    LST_ARMAS VARCHAR(100),
    ID_PARTIDA VARCHAR(8),
    CONSTRAINT FK_ARMAS_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES Partida(ID_PARTIDA),
    CONSTRAINT PK_ARMAS PRIMARY KEY (LST_ARMAS, ID_PARTIDA)
);

CREATE TABLE Padrao(
    ID_PARTIDA VARCHAR(8) PRIMARY KEY,
    CONSTRAINT FK_PADRAO FOREIGN KEY (ID_PARTIDA) REFERENCES Partida(ID_PARTIDA)
);

CREATE TABLE Rounds(
    NUM NUMBER(2, 0),
    ID_PARTIDA VARCHAR(8),
    CONSTRAINT FK_ROUNDS_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES Padrao(ID_PARTIDA),
    CONSTRAINT PK_ROUNDS PRIMARY KEY (NUM, ID_PARTIDA)
);

CREATE TABLE Equipe(
    ID_PARTIDA VARCHAR(8) PRIMARY KEY,
    DIN_GASTO NUMBER(5, 0) NOT NULL,
    ROUNDS_WON NUMBER(2, 0) NOT NULL,
    CONSTRAINT FK_EQUIPE_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES Padrao(ID_PARTIDA)
);

CREATE TABLE Participa(
    ID_PARTIDA VARCHAR(8),
    RIOT_ID VARCHAR(21),
    NOME_AGENTE VARCHAR(30),
    KILLS NUMBER(2, 0),
    DEATHS NUMBER(2, 0),
    ASSISTS NUMBER(2, 0),
    CONSTRAINT FK_PAR_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES Partida(ID_PARTIDA),
    CONSTRAINT FK_PAR_JOG FOREIGN KEY (RIOT_ID) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT FK_PAR_AGENTE FOREIGN KEY (NOME_AGENTE) REFERENCES Agente(NOME_AGENTE),
    CONSTRAINT PK_PARTICIPA PRIMARY KEY (ID_PARTIDA, RIOT_ID)
);

CREATE TABLE FazParte(
    RIOT_ID VARCHAR(21),
    ID_PARTIDA VARCHAR(8),
    CONSTRAINT FK_FAZ_JOG FOREIGN KEY (RIOT_ID) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT FK_POSSUEM_EQ FOREIGN KEY (ID_PARTIDA) REFERENCES Equipe(ID_PARTIDA),
    CONSTRAINT PK_FAZ PRIMARY KEY (RIOT_ID, ID_PARTIDA)
);

CREATE TABLE Possuem(
    RIOT_ID VARCHAR(21),
    ID_SKIN NUMBER(3, 0),
    CONSTRAINT FK_POSSUEM_JOG FOREIGN KEY (RIOT_ID) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT FK_POSSUEM_SKIN FOREIGN KEY (ID_SKIN) REFERENCES Skin(ID_SKIN),
    CONSTRAINT PK_POSSUEM PRIMARY KEY (RIOT_ID, ID_SKIN)
);

CREATE TABLE Ter(
    NOME_ARMA VARCHAR(30),
    ID_SKIN NUMBER(3, 0),
    CONSTRAINT FK_TER_ARMA FOREIGN KEY (NOME_ARMA) REFERENCES Arma(NOME),
    CONSTRAINT FK_TER_SKIN FOREIGN KEY (ID_SKIN) REFERENCES Skin(ID_SKIN),
    CONSTRAINT PK_TER PRIMARY KEY (NOME_ARMA, ID_SKIN)
);

CREATE TABLE Mata(
    MATA VARCHAR(21),
    MORTO VARCHAR(21),
    ARMA VARCHAR(30),
    CONSTRAINT FK_MATA FOREIGN KEY (MATA) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT FK_MORTO FOREIGN KEY (MORTO) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT FK_ARMA FOREIGN KEY (ARMA) REFERENCES Arma(NOME),
    CONSTRAINT PK_MATA PRIMARY KEY (MATA, MORTO, ARMA)
);

CREATE TABLE Amizade(
    ADICIONA VARCHAR(21),
    ADICIONADO VARCHAR(21),
    CONSTRAINT FK_JOGADOR_ADICIONA FOREIGN KEY (ADICIONA) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT FK_JOGADOR_ADICIONADO FOREIGN KEY (ADICIONADO) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT PK_AMIZADE PRIMARY KEY (ADICIONA, ADICIONADO)
);

CREATE TABLE Possui(
    RIOT_ID VARCHAR(21),
    NOME_AGENTE VARCHAR(30),
    CONSTRAINT FK_JOGADOR FOREIGN KEY (RIOT_ID) REFERENCES Jogador(RIOT_ID),
    CONSTRAINT FK_AGENTE FOREIGN KEY (NOME_AGENTE) REFERENCES Agente(NOME_AGENTE),
    CONSTRAINT PK_POSSUI PRIMARY KEY (RIOT_ID, NOME_AGENTE)
);